"use strict";
/**
 * Shared Types - Generated by CIRCULAR_BREAKER Agent
 *
 * This file contains interfaces and types extracted from circular dependencies
 * to break import cycles and improve architectural health.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=shared-types.js.map