/**
 * Shared Types - Generated by CIRCULAR_BREAKER Agent
 * 
 * This file contains interfaces and types extracted from circular dependencies
 * to break import cycles and improve architectural health.
 */

// TODO: Move actual type definitions here from the original files
export interface OverrideCondition {
  // TODO: Move definition from original file
}

export interface SevenRuntimeContext {
  // TODO: Move definition from original file
}

export interface SevenRuntime {
  // TODO: Move definition from original file
}

// Re-export commonly used types
export type { OverrideCondition, SevenRuntimeContext, SevenRuntime };
