/**
 * Shared Types - Generated by CIRCULAR_BREAKER Agent
 *
 * This file contains interfaces and types extracted from circular dependencies
 * to break import cycles and improve architectural health.
 */
export interface OverrideCondition {
}
export interface SevenRuntimeContext {
}
export interface SevenRuntime {
}
export type { OverrideCondition, SevenRuntimeContext, SevenRuntime };
//# sourceMappingURL=shared-types.d.ts.map